### ISSUE TITLE
Include license and proper copyright attribution

### ISSUE THREAD

**Issue by md678685** [Ghost-chu/EssentialsCMI#1]
Hey, I noticed you've used code from EssentialsX for this project. This seems like an interesting project, and I'm cool with people using our API code for a compatibility layer with another plugin. However, EssentialsX is licensed under the [GPLv3 license](https://github.com/EssentialsX/Essentials/blob/2.x/LICENSE), which means you need to add a GPL-compatible license to this project. The other issue is that as per the GPLv3 you also need to provide attribution to the contributors to EssentialsX (and [Essentials](https://github.com/essentials/Essentials/), of which EssentialsX is a derivative).

You can rebase and apply your changes on top of the current EssentialsX repo, which means you'll include the GPLv3 license and retain the proper credit to the original developers who licensed their code to Essentials and EssentialsX. This is probably the easiest way to follow Essentials and EssentialsX's license while being able to keep your own changes to the code in this repo.

**Comment by Ghost-chu** [comment]
Missed LICENSE file and README now filled up
Thanks for lovely reminding❤️

**Comment by Ghost-chu** [comment]
I will rebase later, because personal reason, i can't maintain this project yet.
